language: node_js

node_js:
  - "11"

install:
  - sudo apt-get install hugo

script:
  - npm install -D --save autoprefixer
  - npm install -D --save postcss-cli
  - npm audit fix
  - hugo
  - bash <(curl -s https://peek.run/ci)
  - echo 'gin-gonic.com' > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  on:
    branch: master
