language: node_js

node_js:
 - "11"

install:
 - snap install hugo --channel=extended

script:
  - npm install
  - hugo
  - echo 'gin-gonic.com' > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  on:
    branch: master
